/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Footer } from "./components/homepage-component/homepage-component";
export namespace Components {
    interface HomepageComponent {
        "about": string;
        "apiContent": string;
        "apiTitle": string;
        "footers": Footer[];
        "headline": string;
        "imagePath": string;
        "mainText": string;
        "titleText": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLHomepageComponentElement extends Components.HomepageComponent, HTMLStencilElement {
    }
    var HTMLHomepageComponentElement: {
        prototype: HTMLHomepageComponentElement;
        new (): HTMLHomepageComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "homepage-component": HTMLHomepageComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface HomepageComponent {
        "about"?: string;
        "apiContent"?: string;
        "apiTitle"?: string;
        "footers"?: Footer[];
        "headline"?: string;
        "imagePath"?: string;
        "mainText"?: string;
        "titleText"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "homepage-component": HomepageComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "homepage-component": LocalJSX.HomepageComponent & JSXBase.HTMLAttributes<HTMLHomepageComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
